##
##
---
# Remove Web, App and DB Servers.
- hosts: all
  become: no
  connection: local
  gather_facts: False
  pre_tasks:
    - import_tasks: playbooks/tasks/resolve_target_vm_name.yml
  tasks:
    - name: Remove VMs from vCenter
      community.vmware.vmware_guest:
        hostname: "{{ Target.vCenter.FQDN }}"
        username: "{{ Target.vCenter.User }}"
        password: "{{ Common.Password.Physical }}"
        validate_certs: no
        name: "{{ inventory_hostname }}"
        state: absent
        force: yes
      ignore_errors: yes

# Clean up local templated files
- hosts: 127.0.0.1
  become: no
  connection: local
  gather_facts: False
  vars:
    rendered_template_hosts: >-
      {{
        (
          [Common.hostnames.app | default(groups.get('app', ['app-01a'])[0])] +
          [Common.hostnames.db | default(groups.get('db', ['db-01a'])[0])] +
          (Common.hostnames.web | default(groups.get('web', []))) +
          groups.get('all', [])
        ) | unique
      }}
  tasks:
    - name: Remove templated network config files
      file:
        path: "playbooks/templates/{{ item }}-10-static-eth0.network"
        state: absent
      with_items: "{{ rendered_template_hosts }}"
      ignore_errors: yes

    - name: Remove templated hosts files
      file:
        path: "playbooks/templates/{{ item }}-hosts"
        state: absent
      with_items: "{{ rendered_template_hosts }}"
      ignore_errors: yes

    - name: Display completion message
      debug:
        msg: "VMs have been removed from vCenter"
